apiVersion: apps/v1
kind: Deployment
metadata:
  name: quinto-app-deployment
  labels:
    name: quintopp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quintoapp
  template:
    metadata:
      labels:
        app: quintoapp
    spec:
      containers:
        - name: nodeserver
          image: myregistryrepo.azurecr.io/quintoapp:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: quinto-app-service
spec:
  selector:
    app: quintoapp
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 3000
      nodePort: 31110
